### ISSUE TITLE
curator schedule is hourly

### ISSUE THREAD

**Issue by rschitz** [sexilog/sexilog#10]
it was planned every 5 minutes

**Comment by vmdude** [comment]
Actually `/etc/crontab` contains

`5 * * * * root curator delete --disk-space 10`

Which schedule it every hour at H:05.
If we wanted to switch to every 5 minutes as initially planned, we should update the `/etc/crontab` to

`*/5 * * * * root curator delete --disk-space 10`

**Comment by tsugliani** [comment]
from #16 it seems it should be changed to:

`*/5 * * * * root curator delete --disk-space 10 indices --all-indices`

**Comment by rschitz** [comment]
i did `/15 * * * * root curator delete --disk-space 40 indices --all-indices`

**Comment by rschitz** [comment]
the previous setting was bad syntax, we should do `*/15 * * * * root curator delete --disk-space 40 indices --all-indices`
