### ISSUE TITLE
curator does not delete indices

### ISSUE THREAD

**Issue by shartge** [sexilog/sexilog#16]
The curator command in /etc/crontab is wrong, it does not work:

```
# curator delete --disk-space 40
Usage: curator delete [OPTIONS] COMMAND [ARGS]...

Error: Missing command.
```

Correct usage is:

```
curator delete --disk-space 40 indices --all-indices
```

**Comment by sexilog** [comment]
Thanks sven, we didn't expect syntax change for 3.0



On 27 mars 2015, at 12:35, Sven Hartge <notifications@github.com<mailto:notifications@github.com>> wrote:


The curator command in /etc/crontab is wrong, it does not work:

# curator delete --disk-space 40
Usage: curator delete [OPTIONS] COMMAND [ARGS]...

Error: Missing command.


Correct usage is:

curator delete --disk-space 40 indices --all-indices
