### ISSUE TITLE
Regarding Graylog2 features

### ISSUE THREAD

**Issue by dagnu46** [sexilog/sexilog#18]
Hi Sexi-Team,

I'm searching how to buy the Cyberdyne Plan with my "Gold" card ?

Regards

**Comment by vmdude** [comment]
Franck, Cyberdyne plan will only be available on next major version (or may be the one after).
But sorry you'll not know it, it will upgrade itself and will be self-aware!

**Comment by dagnu46** [comment]
Skynet haz taken your issues.
Thanks for have chosen our "services"
