### ISSUE TITLE
curator cronjob fills mailqueue with junk

### ISSUE THREAD

**Issue by shartge** [sexilog/sexilog#21]
The current curator cronjob is very verbose and generates a useless mail on every run.

Those mails cannot be delivered and create frozen mails in the mail queue because the exim4 daemon on the appliance is only set to do local deliveries and the target user "sexiuser" from `/etc/aliases` does not exist.

But even if the user existed, the mails would still be mostly useless.

I suggest to silence it by adding `--loglevel CRITICAL`:

```
*/15 * * * * root curator --loglevel CRITICAL delete --disk-space 100 indices --all-indices
```

**Comment by rschitz** [comment]
good catch. thanks. done.
