### ISSUE TITLE
wrong rollup timing in riemann.config

### ISSUE THREAD

**Issue by rschitz** [sexilog/sexilog#23]
rollup are in second

**Comment by shartge** [comment]
Umm, please excuse my nosiness, but shouldn't this be fixed in seximenu/conf/riemann.config.sample?

**Comment by rschitz** [comment]
No problem
Yes i did it in the ova package



On 31 mars 2015, at 10:33, Sven Hartge <notifications@github.com<mailto:notifications@github.com>> wrote:


Umm, please excuse my nosiness, but shouldn't this be fixed in seximenu/conf/riemann.config.sample?

**Comment by vmdude** [comment]
The SexiMenu sample configuration file have been updated as well on the GitHub project
