### ISSUE TITLE
Update console resolution

### ISSUE THREAD

**Issue by vmdude** [sexilog/sexilog#24]
We planned on set the console resolution to 1024x768 (instead of the default one).

This is done by editing file `/etc/default/grub` and adding these lines:

`GRUB_GFXMODE=1024x768x32`
`GRUB_GFXPAYLOAD_LINUX=keep`

Then, we ran `update-grub` and reboot

**Comment by rschitz** [comment]
800x600 is enough

**Comment by vmdude** [comment]
So, grub file should contain:

`GRUB_GFXMODE=800x600x32`
`GRUB_GFXPAYLOAD_LINUX=keep`
