### ISSUE TITLE
SexiMenu logout action loop on console

### ISSUE THREAD

**Issue by vmdude** [sexilog/sexilog#25]
'Logout' action (choice 0) loop when user is connected to console (It work as expected when using SSH).

**Comment by vmdude** [comment]
'Logout' action was only killing ssh connexion.

Line 45 should be:
`      0) clear; SSHPID=`ps aux | egrep "sshd: [a-zA-Z]+@" | awk {' print $2 '}`; kill $SSHPID; CONSPID=`ps aux | egrep "tty1.*/bin/login" | grep -v egrep | awk {' print $2 '}`; kill $CONSPID ;;`
to handle SSH and console session

**Comment by vmdude** [comment]
It will be resolved in the next release

**Comment by rschitz** [comment]
not a big deal but it kills root ssh connexions too now
