### ISSUE TITLE
/dev/null all local mails per default

### ISSUE THREAD

**Issue by shartge** [sexilog/sexilog#26]
In addition to issue #21 I would suggest to silence all local mails, which are generated by daily/weekly/monthly cronjobs, etc. which normally nobody will ever read on such an appliance.

Add
```
sexiuser: :blackhole:
```
to `/etc/aliases` to throw all mails away immediately.

If any admin really wants to forward those mails to an external system, he can edit the alias file himself and reconfigure exim4 to use an external smarthost.

**Comment by rschitz** [comment]
done. thanks.
