### ISSUE TITLE
small optimization for vApp

### ISSUE THREAD

**Issue by shartge** [sexilog/sexilog#31]
I noticed some small optimizations are possible for the Debian part of the Sexilog vApp:

Debian Wheezy includes `rpcbind` and `nfs-common` in its default install, but you don't need them unless you use NFS (or something else using RPC calls).

Also the `atd` and `dbus` daemon are running, also not needed for the Sexilog vApp.

And while we are at it, `/var/cache/apt/archives` can be cleaned and the elasticsearch, logstash and riemann DEBs removed from /root/, this saves some bytes to download.

Please do
```
apt-get purge at rpcbind nfs-common dbus
apt-get autoremove
aptitude purge ~c
apt-get clean
rm /root/*.deb
```
to get rid of all unneeded services and bytes.

**Comment by rschitz** [comment]
You rock Sven. i'm testing 0.99g as we speak, i'll add those to the release.

**Comment by rschitz** [comment]
I also removed /root/kibana-proxy and /root/node-startup
