### ISSUE TITLE
Problem with curator ?

### ISSUE THREAD

**Issue by perkooo** [sexilog/sexilog#40]
Hi,

I saw this morning that my disk mounted on /sexilog was full (100%) with 530GB used (Size is 542GB).
Curator disk-space in crontab was set at 500GB, is it normal ?

Thanks

**Comment by vmdude** [comment]
If you try to run manually the curator command, does it say something ?

**Comment by perkooo** [comment]
The command say nothing, I will wait for next rotation (in ~ 10 days) and I tell you (maybe related to full disk/cpu stuck)

**Comment by perkooo** [comment]
Now it looks like it works perfectly ! :) (maybe cpu at 99% was the problem to that)

**Comment by vmdude** [comment]
That's good news !
