### ISSUE TITLE
CPU stuck at 99%

### ISSUE THREAD

**Issue by perkooo** [sexilog/sexilog#41]
Hi,

Since a few days ago, cpu is stuck at 99%, see screen : 
![top](https://cloud.githubusercontent.com/assets/17830838/18241953/4770d1bc-7354-11e6-8657-11ae0b00ed13.jpg)

I tried to reboot the VM or restart services but still the same.

**Comment by vmdude** [comment]
It's typical if there is no space available (garbage collector loop), is this related to #42 ?

**Comment by perkooo** [comment]
Yes, related to #42

**Comment by perkooo** [comment]
Problem solved with #42
